title: CV | Erick VR
description:  Erick Vasquez Rojas CV Online
url: https://erickvr-dev.github.io
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
